const CREATE_USER ='CREATE_USER';
const FETCH_USER ='FETCH_USER';
const UPDATE_USER ='UPDATE_USER';
const DELETE_USER ='DELETE_USER';

const CREATE_PRODUCTS ='CREATE_PRODUCTS';
const FETCH_PRODUCTS ='FETCH_PRODUCTS';
const UPDATE_PRODUCTS ='UPDATE_PRODUCTS';
const DELETE_PRODUCTS ='DELETE_PRODUCTS';

const constants= {
  CREATE_USER,
  FETCH_USER,
  UPDATE_USER,
  DELETE_USER,
  CREATE_PRODUCTS,
  FETCH_PRODUCTS,
  UPDATE_PRODUCTS,
  DELETE_PRODUCTS
}

export default constants;