const orderTypes = {
    SAVE_ORDER_HISTORY_START: 'SAVE_ORDER_HISTORY',
    GET_USER_ORDER_HISTORY_START: 'GET_USER_ORDER_HISTORY_START',
    SET_ORDER_HISTORY: 'SET_ORDER_HISTORY',
    GET_ORDER_DETAIL_START: 'GET_ORDER_DETAIL_START',
    SET_ORDER_DETAIL: 'SET_ORDER_DETAIL'
}

export default orderTypes;